# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configEdit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 447)
        Dialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtApiKey = QtWidgets.QLineEdit(Dialog)
        self.txtApiKey.setObjectName("txtApiKey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtApiKey)
        self.txtCity = QtWidgets.QLineEdit(Dialog)
        self.txtCity.setObjectName("txtCity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtCity)
        self.txtStreet = QtWidgets.QLineEdit(Dialog)
        self.txtStreet.setObjectName("txtStreet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtStreet)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtCounty = QtWidgets.QLineEdit(Dialog)
        self.txtCounty.setObjectName("txtCounty")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtCounty)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtState = QtWidgets.QLineEdit(Dialog)
        self.txtState.setObjectName("txtState")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtState)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtPostCode = QtWidgets.QLineEdit(Dialog)
        self.txtPostCode.setObjectName("txtPostCode")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtPostCode)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.txtWorkDir = QtWidgets.QLineEdit(Dialog)
        self.txtWorkDir.setObjectName("txtWorkDir")
        self.gridLayout.addWidget(self.txtWorkDir, 0, 1, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(Dialog)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtApiKey, self.txtStreet)
        Dialog.setTabOrder(self.txtStreet, self.txtCity)
        Dialog.setTabOrder(self.txtCity, self.txtCounty)
        Dialog.setTabOrder(self.txtCounty, self.txtState)
        Dialog.setTabOrder(self.txtState, self.txtPostCode)
        Dialog.setTabOrder(self.txtPostCode, self.txtWorkDir)
        Dialog.setTabOrder(self.txtWorkDir, self.btnBrowse)
        Dialog.setTabOrder(self.btnBrowse, self.btnOK)
        Dialog.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "API Key"))
        self.label_2.setText(_translate("Dialog", "Home Location"))
        self.label_3.setText(_translate("Dialog", "Street Address"))
        self.label_4.setText(_translate("Dialog", "City"))
        self.label_5.setText(_translate("Dialog", "County"))
        self.label_6.setText(_translate("Dialog", "State"))
        self.txtState.setInputMask(_translate("Dialog", "AA"))
        self.label_7.setText(_translate("Dialog", "Postal Code"))
        self.txtPostCode.setInputMask(_translate("Dialog", "99999"))
        self.label_8.setText(_translate("Dialog", "Working Directory"))
        self.btnBrowse.setText(_translate("Dialog", "Browse"))
        self.btnOK.setText(_translate("Dialog", "Ok"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
