# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 535)
        MainWindow.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.txtAcctID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAcctID.setObjectName("txtAcctID")
        self.gridLayout.addWidget(self.txtAcctID, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.txtClientType = QtWidgets.QLineEdit(self.centralwidget)
        self.txtClientType.setObjectName("txtClientType")
        self.gridLayout.addWidget(self.txtClientType, 4, 2, 1, 1)
        self.txtAcctName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAcctName.setObjectName("txtAcctName")
        self.gridLayout.addWidget(self.txtAcctName, 3, 2, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.txtLoadedFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLoadedFile.setObjectName("txtLoadedFile")
        self.gridLayout.addWidget(self.txtLoadedFile, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.txtAcctOwner = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAcctOwner.setObjectName("txtAcctOwner")
        self.gridLayout.addWidget(self.txtAcctOwner, 5, 2, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayout.addWidget(self.txtAddress, 6, 2, 1, 1)
        self.txtCity = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCity.setObjectName("txtCity")
        self.gridLayout.addWidget(self.txtCity, 7, 2, 1, 1)
        self.txtCounty = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCounty.setObjectName("txtCounty")
        self.gridLayout.addWidget(self.txtCounty, 8, 2, 1, 1)
        self.txtState = QtWidgets.QLineEdit(self.centralwidget)
        self.txtState.setText("")
        self.txtState.setObjectName("txtState")
        self.gridLayout.addWidget(self.txtState, 9, 2, 1, 1)
        self.txtPostalCode = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPostalCode.setObjectName("txtPostalCode")
        self.gridLayout.addWidget(self.txtPostalCode, 10, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit_Config_File = QtWidgets.QAction(MainWindow)
        self.actionEdit_Config_File.setObjectName("actionEdit_Config_File")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtLoadedFile, self.btnBrowse)
        MainWindow.setTabOrder(self.btnBrowse, self.txtAcctID)
        MainWindow.setTabOrder(self.txtAcctID, self.txtAcctName)
        MainWindow.setTabOrder(self.txtAcctName, self.txtClientType)
        MainWindow.setTabOrder(self.txtClientType, self.txtAcctOwner)
        MainWindow.setTabOrder(self.txtAcctOwner, self.txtAddress)
        MainWindow.setTabOrder(self.txtAddress, self.txtCity)
        MainWindow.setTabOrder(self.txtCity, self.txtCounty)
        MainWindow.setTabOrder(self.txtCounty, self.txtState)
        MainWindow.setTabOrder(self.txtState, self.txtPostalCode)
        MainWindow.setTabOrder(self.txtPostalCode, self.btnSave)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AddressAdder"))
        self.label_2.setText(_translate("MainWindow", "Account Name"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Account ID"))
        self.label_3.setText(_translate("MainWindow", "Client Type"))
        self.label_4.setText(_translate("MainWindow", "Account Owner"))
        self.label_9.setText(_translate("MainWindow", "Postal Code"))
        self.label_5.setText(_translate("MainWindow", "Address"))
        self.label_7.setText(_translate("MainWindow", "County"))
        self.label_6.setText(_translate("MainWindow", "City"))
        self.label_8.setText(_translate("MainWindow", "State"))
        self.label_10.setText(_translate("MainWindow", "File Being Edited"))
        self.txtState.setInputMask(_translate("MainWindow", "AA"))
        self.txtPostalCode.setInputMask(_translate("MainWindow", "99999"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnCancel.setText(_translate("MainWindow", "Clear"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.actionEdit_Config_File.setText(_translate("MainWindow", "Edit Config File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
